version: "2.4"

services:
  db:
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: financial_api
      POSTGRES_USER: postgres
    image: postgres:14
    networks: ['mynetwork']
    ports:
      - "5432:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend_container
    volumes:
      - ./backend:/backend
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    networks: ['mynetwork']

networks: {mynetwork: {}}
