# Generated by Django 4.0.1 on 2022-01-21 14:15

from django.db import migrations
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password


def add_users(apps, schema_editor):
    user_model = get_user_model()
    users_to_create = [
        ('Eran', 'Ben-Shushan',),
        ('Catalina', 'Guerra',),
        ('Alex', 'Pliskin',),
        ('Kyle', 'Kammer',)
    ]

    bulk_users = []
    for user_to_create in users_to_create:
        user = user_model(
            first_name=user_to_create[0],
            last_name=user_to_create[1],
            username=user_to_create[0].lower(),
            password=make_password(f'{user_to_create[0]} {user_to_create[1]}')
        )
        bulk_users.append(user)
    user_model.objects.bulk_create(bulk_users)


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_users)
    ]
